### ISSUE TITLE
Importing pook fails on Python 3.11

### ISSUE THREAD

**Issue by martydill** [h2non/pook#84]
Trying to use Pook on Python 3.11 fails:
```
/usr/local/lib/python3.11/site-packages/pook/activate_async.py:2: in <module>
    from asyncio import iscoroutinefunction, coroutine
E   ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/local/lib/python3.11/asyncio/__init__.py)
```

It was removed in 3.11 https://github.com/python/cpython/pull/26369

**Comment by gpxlnx** [comment]
I'm receice this same error when import:

E   AttributeError: module 'asyncio' has no attribute 'coroutine'
_ ERROR collecting .pybuild/cpython3_3.11_pook/build/tests/unit/mock_engine_test.py _
tests/unit/mock_engine_test.py:4: in <module>
    from pook import MockEngine, Engine
pook/__init__.py:1: in <module>
    from .api import *  # noqa
pook/api.py:6: in <module>
    from .engine import Engine
pook/engine.py:5: in <module>
    from .mock_engine import MockEngine
pook/mock_engine.py:1: in <module>
    from .interceptors import interceptors
pook/interceptors/__init__.py:25: in <module>
    from .aiohttp import AIOHTTPInterceptor
pook/interceptors/aiohttp.py:42: in <module>
    class SimpleContent(EmptyStreamReader):
pook/interceptors/aiohttp.py:47: in SimpleContent
    @asyncio.coroutine
E   AttributeError: module 'asyncio' has no attribute 'coroutine'
_ ERROR collecting .pybuild/cpython3_3.11_pook/build/tests/unit/interceptors/module_test.py _
tests/unit/interceptors/module_test.py:1: in <module>

**Comment by KyleJamesWalker** [comment]
Fixed in https://github.com/h2non/pook/pull/83, but it still hasn't' been released.

**Comment by h2non** [comment]
Version `v1.1.0` is now available on PyPI:
`pip install --upgrade pook`

**Comment by gpxlnx** [comment]
Hi,

I am your package maintainer on Debian and derivatives and would like to know if you have any plans to release the latest release on github?

Thanks for your job

**Comment by h2non** [comment]
It is already released and tagged as `v1.1.0`

**Comment by MikhailGurin** [comment]
Hi,
the problem is still there on v1.1.0
/usr/local/lib/python3.11/site-packages/pook/activate_async.py:2: in <module>
from asyncio import iscoroutinefunction, coroutine
ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/local/lib/python3.11/asyncio/__init__.py)

activate_async.py was not fixed in last release

**Comment by h2non** [comment]
FYI - `v1.1.1` is out on PyPI: `pip install --upgrade pook`
